<a href="https://colab.research.google.com/github/jsoook-dt/python-colab-analysis-study/blob/yoonju/Project01_Yoonju_analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Marketing Campaign Analysis**

In [1]:
import pandas as pd
import kagglehub


path = kagglehub.dataset_download("manishabhatt22/marketing-campaign-performance-dataset")
print("Dataset path:", path)

#importing data
df = pd.read_csv(f"{path}/marketing_campaign_dataset.csv")
print("Data Sample:")
display(df.head())

#data types check
print("\nData Information:")
df.info()

Warning: Looks like you're using an outdated `kagglehub` version (installed: 0.3.13), please consider upgrading to the latest version (0.4.1).
Downloading from https://www.kaggle.com/api/v1/datasets/download/manishabhatt22/marketing-campaign-performance-dataset?dataset_version_number=1...

100%|██████████| 5.02M/5.02M [00:00<00:00, 55.2MB/s]

Extracting files...

Dataset path: /root/.cache/kagglehub/datasets/manishabhatt22/marketing-campaign-performance-dataset/versions/1
Data Sample:

,Campaign_ID,Company,Campaign_Type,Target_Audience,Duration,Channel_Used,Conversion_Rate,Acquisition_Cost,ROI,Location,Language,Clicks,Impressions,Engagement_Score,Customer_Segment,Date
0,1,Innovate Industries,Email,Men 18-24,30 days,Google Ads,0.04,"$16,174.00",6.29,Chicago,Spanish,506,1922,6,Health & Wellness,2021-01-01
1,2,NexGen Systems,Email,Women 35-44,60 days,Google Ads,0.12,"$11,566.00",5.61,New York,German,116,7523,7,Fashionistas,2021-01-02
2,3,Alpha Innovations,Influencer,Men 25-34,30 days,YouTube,0.07,"$10,200.00",7.18,Los Angeles,French,584,7698,1,Outdoor Adventurers,2021-01-03
3,4,DataTech Solutions,Display,All Ages,60 days,YouTube,0.11,"$12,724.00",5.55,Miami,Mandarin,217,1820,7,Health & Wellness,2021-01-04
4,5,NexGen Systems,Email,Men 25-34,15 days,YouTube,0.05,"$16,452.00",6.50,Los Angeles,Mandarin,379,4201,3,Health & Wellness,2021-01-05

Data Information:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 200000 entries, 0 to 199999
Data columns (total 16 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   Campaign_ID       200000 non-null  int64
 1   Company           200000 non-null  object
 2   Campaign_Type     200000 non-null  object
 3   Target_Audience   200000 non-null  object
 4   Duration          200000 non-null  object
 5   Channel_Used      200000 non-null  object
 6   Conversion_Rate   200000 non-null  float64
 7   Acquisition_Cost  200000 non-null  object
 8   ROI               200000 non-null  float64
 9   Location          200000 non-null  object
 10  Language          200000 non-null  object
 11  Clicks            200000 non-null  int64
 12  Impressions       200000 non-null  int64
 13  Engagement_Score  200000 non-null  int64
 14  Customer_Segment  200000 non-null  object
 15  Date              200000 non-null  object
dtypes: float64(2), int64(4), object(10)
memory usage: 24.4+ MB

## **Data Cleaning: Analysing individual columns & fixing data types**

**Acquisition cost**

In [2]:
df["Acquisition_Cost"] = (
    df["Acquisition_Cost"]
    .str.replace("$", "", regex=False)
    .str.replace(",", "", regex=False)
    .astype(float)
)

df["Acquisition_Cost"].value_counts()

Acquisition_Cost
16578.0    32
6570.0     31
9128.0     30
8503.0     29
15430.0    29
           ..
7917.0      3
7878.0      3
7443.0      3
14068.0     2
9623.0      2
Name: count, Length: 15001, dtype: int64

**Duration**

In [3]:
df["Duration"] = df["Duration"].str.replace(" days", "", regex=False).astype(int)
df["Duration"].value_counts()

Duration
30    50255
45    50100
60    49866
15    49779
Name: count, dtype: int64

**Date**

In [4]:
df["Date"] = pd.to_datetime(df["Date"])
df["Date"].head()

0   2021-01-01
1   2021-01-02
2   2021-01-03
3   2021-01-04
4   2021-01-05
Name: Date, dtype: datetime64[ns]

In [5]:
df["Company"].value_counts()

Company
TechCorp               40237
Alpha Innovations      40051
DataTech Solutions     40012
NexGen Systems         39991
Innovate Industries    39709
Name: count, dtype: int64

In [6]:
df["Campaign_Type"].value_counts()

Campaign_Type
Influencer      40169
Search          40157
Display         39987
Email           39870
Social Media    39817
Name: count, dtype: int64

In [7]:
df["Target_Audience"].value_counts()

Target_Audience
Men 18-24      40258
Men 25-34      40023
All Ages       40019
Women 25-34    40013
Women 35-44    39687
Name: count, dtype: int64

In [8]:
df["Channel_Used"].value_counts()

Channel_Used
Email         33599
Google Ads    33438
YouTube       33392
Instagram     33392
Website       33360
Facebook      32819
Name: count, dtype: int64

In [9]:
df["Location"].value_counts()

Location
Miami          40269
New York       40024
Chicago        40010
Los Angeles    39947
Houston        39750
Name: count, dtype: int64

In [10]:
df["Language"].value_counts()

Language
Mandarin    40255
Spanish     40102
German      39983
English     39896
French      39764
Name: count, dtype: int64

In [11]:
df["Customer_Segment"].value_counts()

Customer_Segment
Foodies                40208
Tech Enthusiasts       40151
Outdoor Adventurers    40011
Health & Wellness      39888
Fashionistas           39742
Name: count, dtype: int64

**Data cleaning is done, reviewing the cleaned data**

In [12]:
df.head()

,Campaign_ID,Company,Campaign_Type,Target_Audience,Duration,Channel_Used,Conversion_Rate,Acquisition_Cost,ROI,Location,Language,Clicks,Impressions,Engagement_Score,Customer_Segment,Date
0,1,Innovate Industries,Email,Men 18-24,30,Google Ads,0.04,16174.0,6.29,Chicago,Spanish,506,1922,6,Health & Wellness,2021-01-01
1,2,NexGen Systems,Email,Women 35-44,60,Google Ads,0.12,11566.0,5.61,New York,German,116,7523,7,Fashionistas,2021-01-02
2,3,Alpha Innovations,Influencer,Men 25-34,30,YouTube,0.07,10200.0,7.18,Los Angeles,French,584,7698,1,Outdoor Adventurers,2021-01-03
3,4,DataTech Solutions,Display,All Ages,60,YouTube,0.11,12724.0,5.55,Miami,Mandarin,217,1820,7,Health & Wellness,2021-01-04
4,5,NexGen Systems,Email,Men 25-34,15,YouTube,0.05,16452.0,6.50,Los Angeles,Mandarin,379,4201,3,Health & Wellness,2021-01-05

In [13]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 200000 entries, 0 to 199999
Data columns (total 16 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   Campaign_ID       200000 non-null  int64
 1   Company           200000 non-null  object
 2   Campaign_Type     200000 non-null  object
 3   Target_Audience   200000 non-null  object
 4   Duration          200000 non-null  int64
 5   Channel_Used      200000 non-null  object
 6   Conversion_Rate   200000 non-null  float64
 7   Acquisition_Cost  200000 non-null  float64
 8   ROI               200000 non-null  float64
 9   Location          200000 non-null  object
 10  Language          200000 non-null  object
 11  Clicks            200000 non-null  int64
 12  Impressions       200000 non-null  int64
 13  Engagement_Score  200000 non-null  int64
 14  Customer_Segment  200000 non-null  object
 15  Date              200000 non-null  datetime64[ns]
dtypes: datetime64[ns](1), float64(3), int64(5), object(7)
memory usage: 24.4+ MB

# **Exploratory Data Analysis**

**ROI efficiency by Channel**

In [14]:
roi_df = df.groupby("Channel_Used")["ROI"].mean().reset_index()
roi_df = roi_df.sort_values(by="ROI", ascending=False).round(2)
roi_df

  Channel_Used   ROI
1     Facebook  5.02
4      Website  5.01
2   Google Ads  5.00
0        Email  5.00
5      YouTube  4.99
3    Instagram  4.99

**Conversion Rate by Campaign Type**

In [15]:
conversion_df = df.groupby("Campaign_Type")["Conversion_Rate"].mean().reset_index()
conversion_df = conversion_df.sort_values(by="Conversion_Rate", ascending=False)
conversion_df

  Campaign_Type  Conversion_Rate
2    Influencer         0.080315
4  Social Media         0.080135
0       Display         0.080089
3        Search         0.080021
1         Email         0.079788

**ROI VS Conversion**

In [16]:
conversion_roi_df = (
    df.groupby("Campaign_Type")
      .agg(
          Conversion_Rate=("Conversion_Rate", "mean"),
          ROI=("ROI", "mean")
      )
      .reset_index()
)

conversion_roi_df

  Campaign_Type  Conversion_Rate       ROI
0       Display         0.080089  5.006551
1         Email         0.079788  4.994295
2    Influencer         0.080315  5.011068
3        Search         0.080021  5.008357
4  Social Media         0.080135  4.991784

In [18]:
duration_df = df.groupby("Duration")["ROI"].mean().reset_index()
duration_df = duration_df.sort_values(by="ROI", ascending=False)

duration_df

   Duration       ROI
1        30  5.008887
3        60  5.006480
2        45  4.997627
0        15  4.996720